#os: Visual Studio 2015 RC

configuration: Release

before_build:
  - nuget restore
  set path=c:\Tools\NUnit\bin;%path%

#before_test:
  #- ps: start-sleep -s 180
#build_script:
#  - ps: .\build.ps1
